# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aggregator.proto',
  package='aggregator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x61ggregator.proto\x12\naggregator\"C\n\nParameters\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05value\x18\x03 \x03(\x02\x42\x07\n\x05_name\"Y\n\x0bMaskedInput\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08train_id\x18\x02 \x01(\t\x12%\n\x05input\x18\x03 \x03(\x0b\x32\x16.aggregator.Parameters\"U\n\x13MaskedInputResponse\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1b\n\x13\x61ggregate_available\x18\x03 \x01(\x08\"=\n\x16\x41ggregatedInputRequest\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"h\n\x17\x41ggregatedInputResponse\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12*\n\nparameters\x18\x03 \x03(\x0b\x32\x16.aggregator.Parameters2\xc5\x01\n\nAggregator\x12O\n\x11SubmitMaskedInput\x12\x17.aggregator.MaskedInput\x1a\x1f.aggregator.MaskedInputResponse\"\x00\x12\x66\n\x19\x44istributeAggregatedInput\x12\".aggregator.AggregatedInputRequest\x1a#.aggregator.AggregatedInputResponse\"\x00\x62\x06proto3'
)




_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='aggregator.Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='aggregator.Parameters.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='aggregator.Parameters.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='aggregator.Parameters.value', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='aggregator.Parameters._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=32,
  serialized_end=99,
)


_MASKEDINPUT = _descriptor.Descriptor(
  name='MaskedInput',
  full_name='aggregator.MaskedInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='aggregator.MaskedInput.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_id', full_name='aggregator.MaskedInput.train_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input', full_name='aggregator.MaskedInput.input', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=190,
)


_MASKEDINPUTRESPONSE = _descriptor.Descriptor(
  name='MaskedInputResponse',
  full_name='aggregator.MaskedInputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_id', full_name='aggregator.MaskedInputResponse.train_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='aggregator.MaskedInputResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregate_available', full_name='aggregator.MaskedInputResponse.aggregate_available', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=277,
)


_AGGREGATEDINPUTREQUEST = _descriptor.Descriptor(
  name='AggregatedInputRequest',
  full_name='aggregator.AggregatedInputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_id', full_name='aggregator.AggregatedInputRequest.train_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='aggregator.AggregatedInputRequest.client_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=340,
)


_AGGREGATEDINPUTRESPONSE = _descriptor.Descriptor(
  name='AggregatedInputResponse',
  full_name='aggregator.AggregatedInputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_id', full_name='aggregator.AggregatedInputResponse.train_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='success', full_name='aggregator.AggregatedInputResponse.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='aggregator.AggregatedInputResponse.parameters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=446,
)

_PARAMETERS.oneofs_by_name['_name'].fields.append(
  _PARAMETERS.fields_by_name['name'])
_PARAMETERS.fields_by_name['name'].containing_oneof = _PARAMETERS.oneofs_by_name['_name']
_MASKEDINPUT.fields_by_name['input'].message_type = _PARAMETERS
_AGGREGATEDINPUTRESPONSE.fields_by_name['parameters'].message_type = _PARAMETERS
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
DESCRIPTOR.message_types_by_name['MaskedInput'] = _MASKEDINPUT
DESCRIPTOR.message_types_by_name['MaskedInputResponse'] = _MASKEDINPUTRESPONSE
DESCRIPTOR.message_types_by_name['AggregatedInputRequest'] = _AGGREGATEDINPUTREQUEST
DESCRIPTOR.message_types_by_name['AggregatedInputResponse'] = _AGGREGATEDINPUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERS,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:aggregator.Parameters)
  })
_sym_db.RegisterMessage(Parameters)

MaskedInput = _reflection.GeneratedProtocolMessageType('MaskedInput', (_message.Message,), {
  'DESCRIPTOR' : _MASKEDINPUT,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:aggregator.MaskedInput)
  })
_sym_db.RegisterMessage(MaskedInput)

MaskedInputResponse = _reflection.GeneratedProtocolMessageType('MaskedInputResponse', (_message.Message,), {
  'DESCRIPTOR' : _MASKEDINPUTRESPONSE,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:aggregator.MaskedInputResponse)
  })
_sym_db.RegisterMessage(MaskedInputResponse)

AggregatedInputRequest = _reflection.GeneratedProtocolMessageType('AggregatedInputRequest', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEDINPUTREQUEST,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:aggregator.AggregatedInputRequest)
  })
_sym_db.RegisterMessage(AggregatedInputRequest)

AggregatedInputResponse = _reflection.GeneratedProtocolMessageType('AggregatedInputResponse', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEDINPUTRESPONSE,
  '__module__' : 'aggregator_pb2'
  # @@protoc_insertion_point(class_scope:aggregator.AggregatedInputResponse)
  })
_sym_db.RegisterMessage(AggregatedInputResponse)



_AGGREGATOR = _descriptor.ServiceDescriptor(
  name='Aggregator',
  full_name='aggregator.Aggregator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=449,
  serialized_end=646,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitMaskedInput',
    full_name='aggregator.Aggregator.SubmitMaskedInput',
    index=0,
    containing_service=None,
    input_type=_MASKEDINPUT,
    output_type=_MASKEDINPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DistributeAggregatedInput',
    full_name='aggregator.Aggregator.DistributeAggregatedInput',
    index=1,
    containing_service=None,
    input_type=_AGGREGATEDINPUTREQUEST,
    output_type=_AGGREGATEDINPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGGREGATOR)

DESCRIPTOR.services_by_name['Aggregator'] = _AGGREGATOR

# @@protoc_insertion_point(module_scope)
