version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev_db
    ports:
      - "5452:5432"