FROM python:3.10-slim
RUN apt-get -yqq update && apt-get -yqq upgrade && pip install pipenv

COPY ./Pipfile ./Pipfile.lock /opt/federated/

WORKDIR /opt/federated/

RUN pipenv install --system
COPY . /opt/federated/

RUN pip install .


CMD ["uvicorn",  "pht_federated.aggregator.app:app", "--port", "8000", "--host", "0.0.0.0"]
